In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

### Data Exploration and Preprocessing

In [2]:
# loading data
data = pd.read_csv('Alphabets_data.csv')
data

,letter,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,T,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,N,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,G,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,D,2,2,3,3,2,7,7,7,6,6,6,4,2,8,3,7
19996,C,7,10,8,8,4,4,8,6,9,12,9,13,2,9,3,7
19997,T,6,9,6,7,5,6,11,3,7,11,9,5,2,12,2,4
19998,S,2,3,4,2,1,8,7,2,6,10,6,8,1,9,5,8
19999,A,4,9,6,6,2,9,5,3,1,8,1,8,2,7,2,8

In [3]:
data.shape

(20000, 17)

In [4]:
data.columns

Index(['letter', 'xbox', 'ybox', 'width', 'height', 'onpix', 'xbar', 'ybar',
       'x2bar', 'y2bar', 'xybar', 'x2ybar', 'xy2bar', 'xedge', 'xedgey',
       'yedge', 'yedgex'],
      dtype='object')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   letter  20000 non-null  object
 1   xbox    20000 non-null  int64
 2   ybox    20000 non-null  int64
 3   width   20000 non-null  int64
 4   height  20000 non-null  int64
 5   onpix   20000 non-null  int64
 6   xbar    20000 non-null  int64
 7   ybar    20000 non-null  int64
 8   x2bar   20000 non-null  int64
 9   y2bar   20000 non-null  int64
 10  xybar   20000 non-null  int64
 11  x2ybar  20000 non-null  int64
 12  xy2bar  20000 non-null  int64
 13  xedge   20000 non-null  int64
 14  xedgey  20000 non-null  int64
 15  yedge   20000 non-null  int64
 16  yedgex  20000 non-null  int64
dtypes: int64(16), object(1)
memory usage: 2.6+ MB

In [6]:
data.nunique()

letter    26
xbox      16
ybox      16
width     16
height    16
onpix     16
xbar      16
ybar      16
x2bar     16
y2bar     16
xybar     16
x2ybar    16
xy2bar    16
xedge     16
xedgey    16
yedge     16
yedgex    16
dtype: int64

In [7]:
data.isna().sum()

letter    0
xbox      0
ybox      0
width     0
height    0
onpix     0
xbar      0
ybar      0
x2bar     0
y2bar     0
xybar     0
x2ybar    0
xy2bar    0
xedge     0
xedgey    0
yedge     0
yedgex    0
dtype: int64

In [8]:
data.duplicated().sum()

np.int64(1332)

In [9]:
data.drop_duplicates(ignore_index=True,inplace=True)

In [10]:
data.shape

(18668, 17)

In [11]:
data['letter'].value_counts()

letter
P    782
U    768
D    760
Q    760
A    756
F    752
T    748
Y    746
G    743
R    737
M    732
B    730
S    729
W    726
E    725
O    718
K    718
J    715
C    710
V    706
H    704
N    688
X    678
L    673
Z    640
I    524
Name: count, dtype: int64

In [12]:
data.describe()

,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
count,18668.000000,18668.000000,18668.000000,18668.000000,18668.000000,18668.000000,18668.000000,18668.000000,18668.000000,18668.000000,18668.000000,18668.000000,18668.000000,18668.000000,18668.000000,18668.000000
mean,4.150793,7.244322,5.279891,5.506910,3.660596,6.919381,7.529409,4.584637,5.201361,8.353171,6.452700,7.924577,3.131455,8.351832,3.796872,7.784390
std,1.879428,3.187660,1.934960,2.178292,2.160555,2.032226,2.319834,2.625714,2.320102,2.468905,2.624673,2.106957,2.323901,1.574853,2.540271,1.657358
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,5.000000,4.000000,4.000000,2.000000,6.000000,6.000000,3.000000,4.000000,7.000000,5.000000,7.000000,2.000000,8.000000,2.000000,7.000000
50%,4.000000,8.000000,5.000000,6.000000,3.000000,7.000000,7.000000,4.000000,5.000000,8.000000,6.000000,8.000000,3.000000,8.000000,4.000000,8.000000
75%,5.000000,10.000000,6.000000,7.000000,5.000000,8.000000,9.000000,6.000000,7.000000,10.000000,8.000000,9.000000,4.000000,9.000000,5.000000,9.000000
max,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000

### Model Implementation`

In [13]:
X = data.drop('letter',axis=1)
y = data['letter']

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
le = LabelEncoder()
y = le.fit_transform(y)

#### normalization

In [16]:
from sklearn.preprocessing import MinMaxScaler

In [17]:
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

#### Divide the dataset into training and test sets.

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((14934, 16), (3734, 16), (14934,), (3734,))

#### basic ANN model

In [20]:
!pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\raghavendra g n\anaconda3\lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (25.0)
Collecting protobuf<8.0.0,>=6.31.1 (from tensorflow)
  Downloading protobuf-7.34.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (1.78.0)
Requirement already satisfied: keras>=3.12.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (2.3.5)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.1.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\users\raghavendra g n\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (14.2.0)
Requirement already satisfied: namex in c:\users\raghavendra g n\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\raghavendra g n\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Downloading protobuf-7.34.1-cp310-abi3-win_amd64.whl (437 kB)
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 6.31.0
    Uninstalling protobuf-6.31.0:
      Successfully uninstalled protobuf-6.31.0
Successfully installed protobuf-7.34.1

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.51.0 requires protobuf<7,>=3.20, but you have protobuf 7.34.1 which is incompatible.

In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Input
from tensorflow.keras.utils import to_categorical

In [22]:
model = Sequential([
    Input(shape=(X_train.shape[1],)),
    Dense(64,activation='relu'),
    Dense(32,activation='relu'),
    Dense(26,activation='softmax')
])

In [23]:
model.compile(optimizer = 'adam',
            loss='sparse_categorical_crossentropy',
            metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

#### train the model

In [24]:
history = model.fit(X_train,y_train,
                   validation_split=0.2,
                   epochs=30,
                   batch_size=32,
                   verbose=1)

Epoch 1/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.2057 - loss: 2.8379 - val_accuracy: 0.3870 - val_loss: 2.2168
Epoch 2/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.4902 - loss: 1.8819 - val_accuracy: 0.5166 - val_loss: 1.6952
Epoch 3/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.5694 - loss: 1.5640 - val_accuracy: 0.5732 - val_loss: 1.5163
Epoch 4/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.6144 - loss: 1.4092 - val_accuracy: 0.6090 - val_loss: 1.3991
Epoch 5/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.6394 - loss: 1.3052 - val_accuracy: 0.6398 - val_loss: 1.3209
Epoch 6/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.6610 - loss: 1.2329 - val_accuracy: 0.6696 - val_loss: 1.2437
Epoch 7/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.6775 - loss: 1.1735 - val_accuracy: 0.6753 - val_loss: 1.2102
Epoch 8/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.6832 - loss: 1.1326 - val_accuracy: 0.6746 - val_loss: 1.1706
Epoch 9/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.6927 - loss: 1.0983 - val_accuracy: 0.6806 - val_loss: 1.1504
Epoch 10/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7044 - loss: 1.0673 - val_accuracy: 0.6947 - val_loss: 1.1170
Epoch 11/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7092 - loss: 1.0438 - val_accuracy: 0.6984 - val_loss: 1.0939
Epoch 12/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7133 - loss: 1.0187 - val_accuracy: 0.6953 - val_loss: 1.0926
Epoch 13/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7202 - loss: 1.0008 - val_accuracy: 0.7054 - val_loss: 1.0560
Epoch 14/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7259 - loss: 0.9812 - val_accuracy: 0.6967 - val_loss: 1.0494
Epoch 15/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7253 - loss: 0.9681 - val_accuracy: 0.7218 - val_loss: 1.0208
Epoch 16/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7340 - loss: 0.9511 - val_accuracy: 0.7201 - val_loss: 1.0032
Epoch 17/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7351 - loss: 0.9323 - val_accuracy: 0.7198 - val_loss: 0.9905
Epoch 18/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7405 - loss: 0.9207 - val_accuracy: 0.7258 - val_loss: 0.9828
Epoch 19/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7435 - loss: 0.9078 - val_accuracy: 0.7275 - val_loss: 0.9535
Epoch 20/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.7467 - loss: 0.8927 - val_accuracy: 0.7288 - val_loss: 0.9558
Epoch 21/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7494 - loss: 0.8779 - val_accuracy: 0.7338 - val_loss: 0.9362
Epoch 22/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7538 - loss: 0.8664 - val_accuracy: 0.7479 - val_loss: 0.9020
Epoch 23/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7569 - loss: 0.8513 - val_accuracy: 0.7389 - val_loss: 0.9019
Epoch 24/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7630 - loss: 0.8370 - val_accuracy: 0.7469 - val_loss: 0.9029
Epoch 25/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7650 - loss: 0.8252 - val_accuracy: 0.7476 - val_loss: 0.8850
Epoch 26/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7664 - loss: 0.8175 - val_accuracy: 0.7533 - val_loss: 0.8680
Epoch 27/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7705 - loss: 0.8038 - val_accuracy: 0.7533 - val_loss: 0.8593
Epoch 28/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7716 - loss: 0.7956 - val_accuracy: 0.7583 - val_loss: 0.8370
Epoch 29/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7733 - loss: 0.7827 - val_accuracy: 0.7543 - val_loss: 0.8416
Epoch 30/30
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7746 - loss: 0.7736 - val_accuracy: 0.7630 - val_loss: 0.8255

#### evaluate on test data

In [25]:
test_loss,test_acc = model.evaluate(X_test,y_test)
print(f'test accuracy: {test_acc:.3f}')

117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7788 - loss: 0.8011
test accuracy: 0.779

### Hyperparameter Tuning

In [26]:
!pip uninstall -y tensorflow-estimator

WARNING: Skipping tensorflow-estimator as it is not installed.

In [27]:
!pip install scikeras

Collecting scikeras
  Downloading scikeras-0.13.0-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: keras>=3.2.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from scikeras) (3.13.2)
Requirement already satisfied: scikit-learn>=1.4.2 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from scikeras) (1.8.0)
Requirement already satisfied: absl-py in c:\users\raghavendra g n\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (2.4.0)
Requirement already satisfied: numpy in c:\users\raghavendra g n\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (2.3.5)
Requirement already satisfied: rich in c:\users\raghavendra g n\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (14.2.0)
Requirement already satisfied: namex in c:\users\raghavendra g n\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (0.1.0)
Requirement already satisfied: h5py in c:\users\raghavendra g n\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (3.14.0)
Requirement already satisfied: optree in c:\users\raghavendra g n\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (0.19.0)
Requirement already satisfied: ml-dtypes in c:\users\raghavendra g n\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (0.5.4)
Requirement already satisfied: packaging in c:\users\raghavendra g n\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (25.0)
Requirement already satisfied: scipy>=1.10.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from scikit-learn>=1.4.2->scikeras) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from scikit-learn>=1.4.2->scikeras) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from scikit-learn>=1.4.2->scikeras) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from optree->keras>=3.2.0->scikeras) (4.15.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from rich->keras>=3.2.0->scikeras) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from rich->keras>=3.2.0->scikeras) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->scikeras) (0.1.2)
Downloading scikeras-0.13.0-py3-none-any.whl (26 kB)
Installing collected packages: scikeras
Successfully installed scikeras-0.13.0

In [28]:
!pip install scikeras --upgrade
!pip install tensorflow --upgrade
!pip install scikit-learn --upgrade

Requirement already satisfied: scikeras in c:\users\raghavendra g n\anaconda3\lib\site-packages (0.13.0)
Requirement already satisfied: keras>=3.2.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from scikeras) (3.13.2)
Requirement already satisfied: scikit-learn>=1.4.2 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from scikeras) (1.8.0)
Requirement already satisfied: absl-py in c:\users\raghavendra g n\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (2.4.0)
Requirement already satisfied: numpy in c:\users\raghavendra g n\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (2.3.5)
Requirement already satisfied: rich in c:\users\raghavendra g n\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (14.2.0)
Requirement already satisfied: namex in c:\users\raghavendra g n\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (0.1.0)
Requirement already satisfied: h5py in c:\users\raghavendra g n\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (3.14.0)
Requirement already satisfied: optree in c:\users\raghavendra g n\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (0.19.0)
Requirement already satisfied: ml-dtypes in c:\users\raghavendra g n\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (0.5.4)
Requirement already satisfied: packaging in c:\users\raghavendra g n\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (25.0)
Requirement already satisfied: scipy>=1.10.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from scikit-learn>=1.4.2->scikeras) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from scikit-learn>=1.4.2->scikeras) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from scikit-learn>=1.4.2->scikeras) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from optree->keras>=3.2.0->scikeras) (4.15.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from rich->keras>=3.2.0->scikeras) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from rich->keras>=3.2.0->scikeras) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->scikeras) (0.1.2)
Requirement already satisfied: tensorflow in c:\users\raghavendra g n\anaconda3\lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (7.34.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (1.78.0)
Requirement already satisfied: keras>=3.12.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (2.3.5)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.1.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\users\raghavendra g n\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (14.2.0)
Requirement already satisfied: namex in c:\users\raghavendra g n\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\raghavendra g n\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Requirement already satisfied: scikit-learn in c:\users\raghavendra g n\anaconda3\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from scikit-learn) (2.3.5)
Requirement already satisfied: scipy>=1.10.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\raghavendra g n\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)

In [29]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import GridSearchCV

In [30]:
def create_model(neurons=64,activation='relu',optimizer='adam'):
    model = Sequential()
    model.add(Dense(neurons,input_dim=X_train.shape[1],activation=activation))
    model.add(Dense(neurons//2,activation=activation))
    model.add(Dense(1,activation='sigmoid'))
    model.compile(loss='binary_crossentropy',optimizer=optimizer,metrics=['accuracy'])
    return model

In [31]:
model1 = KerasClassifier(model=create_model,verbose=0)

In [32]:
param_grid={
    'model__neurons':[32,64,128],
    'model__activation':['relu','tanh'],
    'model__optimizer':['adam','sgd']
}

In [33]:
grid = GridSearchCV(estimator=model1,param_grid=param_grid,cv=3)

In [34]:
grid_result = grid.fit(X_train, y_train)

C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Raghavendra G N\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [35]:
print(f'best:{grid_result.best_score_} using {grid_result.best_params_}')

best:0.04098031337886702 using {'model__activation': 'relu', 'model__neurons': 32, 'model__optimizer': 'adam'}

### model evaluation

In [36]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix,classification_report

In [37]:
def evaluate_model(y_test,y_pred):
    ac = accuracy_score(y_test,y_pred)
    ps = precision_score(y_test,y_pred,average='weighted',zero_division=1)
    rs = recall_score(y_test,y_pred,average='weighted')
    f1 = f1_score(y_test,y_pred,average='weighted')

    print(f'performance:')
    print(f'accuracy : {ac:.3f}')
    print(f'precision : {ps:.3f}')
    print(f'recall : {rs:.3f}')
    print(f'f1-score : {f1:.3f}')
    print('confusion matrix :')
    print(confusion_matrix(y_test,y_pred))
    print('classification report :')
    print(classification_report(y_test,y_pred,zero_division=1))

In [38]:
#for default ANN model
y_pred_default = model.predict(X_test)
y_pred_default = y_pred_default.argmax(axis=1)
evaluate_model(y_test,y_pred_default)

117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
performance:
accuracy : 0.779
precision : 0.781
recall : 0.779
f1-score : 0.778
confusion matrix :
[[128   0   0   1   0   0   0   0   0   3   3   0   1   0   0   0   0   0
    3   0   2   0   0   2   1   0]
 [  0 122   0   3   2   2   3   4   1   0   0   0   0   0   0   6   1  10
    1   0   0   0   0   1   0   0]
 [  0   0 105   0   9   0   4   0   1   1   9   0   2   0   7   0   0   0
    4   3   2   0   0   0   0   0]
 [  0   5   0 125   0   0   1   1   0   2   0   1   0   4   6   4   0   2
    1   6   0   0   0   2   0   3]
 [  0   3   2   0 108   0   4   0   2   0   2   6   0   0   0   0   5   2
    5   0   0   0   0   4   0   1]
 [  1   2   1   1   3 123   1   1   3   0   0   0   0   0   0   5   0   0
    0   5   0   0   0   0   0   0]
 [  1   2   9   3   0   0 116   0   2   0   7   2   0   0   6   1  11   4
    2   0   0   6   1   0   0   0]
 [  3   2   0   8   0   3   0  77   1   0   7   0   0   6   5   2   4   8
    0   0   0   6   0   1   0   0]
 [  0   0   0   1   0   2   0   0  88   5   0   3   0   0   0   2   0   0
    5   0   0   0   0   1   1   0]
 [  2   0   0   2   0   1   0   3   7 128   0   0   0   0   0   0   0   0
    4   0   0   0   0   1   0   2]
 [  0   1   2   1   2   0   1   1   0   0 128   1   1   2   0   0   0   6
    1   0   1   0   0   1   0   0]
 [  0   0   0   0   4   0   7   2   0   0   4 120   0   1   0   0   1   1
    2   2   0   0   0   3   0   0]
 [  0   0   0   2   0   0   0   3   0   0   0   0 130   2   0   0   0   3
    0   0   1   0   2   0   0   0]
 [  2   1   0   2   0   0   0   3   0   0   5   0   1 116   3   2   0   0
    0   0   1   1   1   0   0   0]
 [  2   0   0   9   0   0   3   2   0   0   0   0   1   1  96   4   4   3
    0   0   0   1   5   0   0   0]
 [  1   0   0   1   0   9   5   0   0   0   0   0   0   0   3 132   0   0
    0   0   0   1   0   0   9   0]
 [  5   2   1   0   1   0   2   2   0   1   0   0   0   0   4   1 113   0
    8   0   0   0   1   1   1   2]
 [  1   5   0   0   3   0   1   3   0   0  16   1   0   0   0   1   0 115
    0   0   0   0   0   1   0   0]
 [  1   4   0   1   2   8   1   0   6   4   0   9   0   0   0   2   3   0
   81   0   0   0   0   1   4  15]
 [  0   1   0   1   3  13   4   2   7   0   3   0   0   0   0   0   0   0
    1 102   0   4   0   4   4   2]
 [  1   0   0   0   0   0   1   2   0   0   0   0   3   9   5   0   0   1
    0   0 116   1   3   1   0   0]
 [  0   1   0   1   0   0   2   2   0   0   0   0   0   0   2   2   0   4
    0   0   0 131   2   0   8   0]
 [  1   0   0   1   0   0   0   5   0   0   0   0   2   1   5   0   0   0
    0   0   0   1 117   0   0   0]
 [  0   1   0   3   4   0   0   3   3   1   2   4   0   0   0   0   8   0
    0   1   1   0   0  91   1   1]
 [  0   0   0   2   0   6   0   0   2   2   0   0   0   0   0   2   6   0
    0   5   1   9   0   3 100   0]
 [  0   0   0   1   3   1   0   0   0   8   0   0   0   0   0   0   0   0
    9   0   0   0   0   1   0 100]]
classification report :
              precision    recall  f1-score   support

           0       0.86      0.89      0.87       144
           1       0.80      0.78      0.79       156
           2       0.88      0.71      0.79       147
           3       0.74      0.77      0.75       163
           4       0.75      0.75      0.75       144
           5       0.73      0.84      0.78       146
           6       0.74      0.67      0.71       173
           7       0.66      0.58      0.62       133
           8       0.72      0.81      0.76       108
           9       0.83      0.85      0.84       150
          10       0.69      0.86      0.76       149
          11       0.82      0.82      0.82       147
          12       0.92      0.91      0.92       143
          13       0.82      0.84      0.83       138
          14       0.68      0.73      0.70       131
          15       0.80      0.82      0.81       161
          16       0.72      0.78      0.75       145
          17       0.72      0.78      0.75       147
          18       0.64      0.57      0.60       142
          19       0.82      0.68      0.74       151
          20       0.93      0.81      0.87       143
          21       0.81      0.85      0.83       155
          22       0.89      0.88      0.88       133
          23       0.76      0.73      0.75       124
          24       0.78      0.72      0.75       138
          25       0.79      0.81      0.80       123

    accuracy                           0.78      3734
   macro avg       0.78      0.78      0.78      3734
weighted avg       0.78      0.78      0.78      3734

In [39]:
#for tunined model
y_pred_tuned = grid_result.best_estimator_.predict(X_test)
evaluate_model(y_test,y_pred_tuned)

performance:
accuracy : 0.039
precision : 0.963
recall : 0.039
f1-score : 0.003
confusion matrix :
[[144   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [156   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [147   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [163   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [144   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [146   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [173   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [133   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [108   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [150   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [149   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [147   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [143   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [138   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [131   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [161   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [145   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [147   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [142   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [151   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [143   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [155   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [133   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [124   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [138   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [123   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]]
classification report :
              precision    recall  f1-score   support

           0       0.04      1.00      0.07       144
           1       1.00      0.00      0.00       156
           2       1.00      0.00      0.00       147
           3       1.00      0.00      0.00       163
           4       1.00      0.00      0.00       144
           5       1.00      0.00      0.00       146
           6       1.00      0.00      0.00       173
           7       1.00      0.00      0.00       133
           8       1.00      0.00      0.00       108
           9       1.00      0.00      0.00       150
          10       1.00      0.00      0.00       149
          11       1.00      0.00      0.00       147
          12       1.00      0.00      0.00       143
          13       1.00      0.00      0.00       138
          14       1.00      0.00      0.00       131
          15       1.00      0.00      0.00       161
          16       1.00      0.00      0.00       145
          17       1.00      0.00      0.00       147
          18       1.00      0.00      0.00       142
          19       1.00      0.00      0.00       151
          20       1.00      0.00      0.00       143
          21       1.00      0.00      0.00       155
          22       1.00      0.00      0.00       133
          23       1.00      0.00      0.00       124
          24       1.00      0.00      0.00       138
          25       1.00      0.00      0.00       123

    accuracy                           0.04      3734
   macro avg       0.96      0.04      0.00      3734
weighted avg       0.96      0.04      0.00      3734

#### default model:
#### basic hyperparameters, may misclassify some classes, moderate accuracy.
#### tuned model:
#### optimized layers,neurons,activation,learning rate,etc..
#### usually higher accuracy,precision,recall,f1-score,better generalization